CREATE TABLE scores (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   player_name VARCHAR(150) NOT NULL DEFAULT 'anonymous',
   player_score INT(10) UNSIGNED NOT NULL DEFAULT '0',
   player_type VARCHAR(150) NOT NULL DEFAULT 'Manual'
);